name: 'OnlineStoreFront $(builderCounter)'
trigger:
- develop
variables:
  -  name: builderCounter
     value: $[counter('builderCounter', 1)]
stages:
- stage: BuildApplication
  displayName: 'BuildOnlineStoreFront'
  jobs:
  - deployment: BuildApplication
    displayName: Build Web App Frontend
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'BuildOnlineStoreFront'
    strategy:
      runOnce:
        deploy:

          steps:
              - checkout: self
              - task: NodeTool@0
                displayName: 'Install Node.js'
                inputs:
                  versionSpec: '18.x'
              - script: |
                          npm install
                          npm run build
                displayName: 'npm install build'
              - task: PublishBuildArtifacts@1
                inputs:
                  PathtoPublish: 'build'
                  ArtifactName: 'drop'
                  publishLocation: 'Container'

- stage: Deploy
  displayName: 'DeployOnlineStoreFront'
  jobs:
    - deployment: DeployOnlineStoreFront
      displayName: Deploy Web App Frontend
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'DeployOnlineStoreFront'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                targetPath: '$(System.DefaultWorkingDirectory)'
                artifactName: drop
            - task: AzureWebApp@1
              inputs:
                  azureSubscription: 'sc-arm'
                  appType: 'webApp'
                  appName: 'roistore'
                  package: '$(System.DefaultWorkingDirectory)'
                  deploymentMethod: 'runFromPackage'