trigger:
- main

stages:
- stage: BuildApplication
  displayName: 'BuildOnlineStoreBack'
  jobs:
    - job: BuildOnlineStoreBack
      displayName: Build Web App Backend
      variables:
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'
        solution: '**/OnlineStore.sln'
        project: '**/OnlineStore.API.csproj'
      pool:
          vmImage: 'windows-2022'
      steps:    
        - checkout: git://HomeWork/OnlineStore.Backend

        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: restore
            projects: '$(project)'
          
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            projects: '$(project)'
            arguments: '--configuration $(BuildConfiguration)'
      
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      
        - task: DotNetCoreCLI@2
          name: 'Tests'
          displayName: 'Run tests'
          inputs:
              command: 'test'
              projects: '$(project)'
              arguments: '--configuration $(BuildConfiguration)'


        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'




- stage: Deploy
  displayName: 'DeployOnlineStoreBack'
  jobs:
    - deployment: DeployOnlineStoreBack
      displayName: Deploy Web App Backend
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'DeployOnlineStoreBack'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                targetPath: '$(System.DefaultWorkingDirectory)'
                artifactName: drop


            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'sc-arm'
                appType: 'webApp'
                appName: 'roistoreback'
                package: '$(System.DefaultWorkingDirectory)/**/*.zip'
                deploymentMethod: 'zipDeploy'

            